---
# Borrowed from percona xtradb cluster ansible role:
# https://github.com/cdelgehier/ansible-role-XtraDB-Cluster/blob/master/tasks/postinstall.yml
# Many thanks to Cedric DELGEHIER
- name: mysql_databases | create the databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
  with_items: "{{ mariadb_databases }}"
  become: true
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  register: _db

- name: mysql_databases | copy database init scripts
  copy: # noqa 503
    src: "{{ item.item.init_script }}"
    dest: "/tmp/{{ item.item.init_script | basename }}"
    mode: "0600"
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined

- name: mysql_databases | initialise databases
  mysql_db: # noqa 503
    name: "{{ item.item.name }}"
    state: import
    target: "/tmp/{{ item.item.init_script | basename }}"
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
  with_items: "{{ _db.results }}"
  become: true
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  when:
    - item.changed
    - item.item.init_script is defined

- name: mysql_databases | delete init scripts from the server
  file: # noqa 503
    name: "/tmp/{{ item.item.init_script | basename }}"
    state: absent
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  with_items: "{{ _db.results }}"
  when:
    - item.changed
    - item.item.init_script is defined
